# Generated by Django 6.0 on 2026-01-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_image_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
